#!/bin/sh
#
# This is your typical `musl-gcc` wrapper script, but configured to use
# the appropriate musl build in the docker image.
exec "x86_64-linux-gnu-gcc" "$@" -specs "${MUSL_PREFIX:-/musl}/amd64/lib/musl-gcc.specs"
