# This workflow checks that the contents of the PR are ready for
# publishing as soon as they land in `main`. Most importantly it
# checks that a new version number has been assigned as part of the
# change and it's basically consistent with our release policy.

name: Check that a PR is ready for merge to main

on:
  pull_request:
    branches: [main]

env:
  GITHUB_BASE_SHA: ${{ github.event.pull_request.base.sha }}
  GITHUB_HEAD_SHA: ${{ github.event.pull_request.head.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Check version number consistency
        run: ./scripts/check-pr.sh

      - name: Set up QEMU for Docker
        uses: docker/setup-qemu-action@v2
        with:
            platforms: arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache docker build artifacts
        uses: actions/cache@v2
        with:
          path: |
            /tmp/buildx-cache/
          key: docker-buildx-${{ hashFiles('./Makefile', './Dockerfile', './scripts/*') }}
          restore-keys: |
            docker-buildx-

      - name: Check that the images can be built and used
        run: make test

      - name: Only keep the latest images in docker cache
        run: |
          rm -rf /tmp/buildx-cache
          mv /tmp/buildx-cache-new /tmp/buildx-cache

